Fitness_App_Final/WorkoutTrackingApp/Controllers/UserProfileDashboardController.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Cryptography.X509Certificates;
using WorkoutTrackingApp.ViewModels;
using System;
using System.Collections.Generic; // this is for List<T>
using Microsoft.AspNetCore.Authorization;
using WorkoutTrackingApp.Data;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using WorkoutTrackingApp.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Identity.Client;

// Central hub for user dashboard
// Here I can incorporate latest workout/ or workouts, don't need a profile picture i don't think, profile view was completly unneccesary since the index is the profile
// Don't need to manage subscription as a user so that view was deleted
// Basic Settings view can be integrated here into the index I think, possibly. 
namespace WorkoutTrackingApp.Controllers
{
    /// <summary>
    /// This controller is for managing the user dashboard and the user profile. Provides
    /// ablilities to view workouts, track workouts, and send messages. 
    /// </summary>
    public class UserProfileDashboardController : Controller
    {
        private readonly WorkoutTrackingAppContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public UserProfileDashboardController(WorkoutTrackingAppContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        /// <summary>
        /// Shows the main dashboard for a user and recent workouts too. 
        /// </summary>
        /// <returns>The view of the user dashbaord.</returns>
        [Authorize]
        public async Task<IActionResult> Index()
        {
            // Get the current Identity user's ID
            var identityUserId = _userManager.GetUserId(User);

            // Find the corresponding account
            var userAccount = await _context.Accounts
                                            .FirstOrDefaultAsync(a => a.IdentityUserId == identityUserId);

            if (userAccount == null)
            {
                return NotFound(); // or handle appropriately
            }

            var userId = userAccount.AccountId;

            // Fetch recent tracked workouts including the workout details
            var recentTrackedWorkouts = await _context.TrackedWorkouts
                .Where(tw => tw.AccountId == userId)
                .OrderByDescending(tw => tw.DateCompleted)
                .Take(10)
                .Include(tw => tw.Workout) // Include the Workout entity
                .ToListAsync();

            // Map to WorkoutViewModels
            var workoutViewModels = recentTrackedWorkouts.Select(tw => new WorkoutViewModel
            {
                WorkoutID = tw.Workout.WorkoutId,
                Name = tw.Workout.Name,
                Author = tw.Workout.Author,
                Description = tw.Workout.Description,
                DateCompleted = tw.DateCompleted // Include the DateCompleted
            }).ToList();

            var messageViewModel = new MessageViewModel
            {
                Trainers = await GetTrainersList()
            };

            var viewModel = new UserDashboardViewModel
            {
                UserName = (await _userManager.FindByIdAsync(identityUserId))?.Email,
                Email = (await _userManager.FindByIdAsync(identityUserId))?.Email,
                RecentWorkouts = workoutViewModels,
                SendMessageViewModel = messageViewModel
            };

            return View(viewModel);
        }

        /// <summary>
        /// Shows a list of workouts for the user of which they can track.
        /// </summary>
        /// <returns>A view that has a list of workouts they can click to track from.</returns>
        [Authorize]
        public async Task<IActionResult> SelectedWorkouts()
        {
            var workouts = await _context.Workouts
                                .Select(w => new WorkoutViewModel
                                {
                                    //Putting Workout properties to WorkoutViewModel
                                    WorkoutID = w.WorkoutId,
                                    Name = w.Name,
                                    Description = w.Description,                                 
                                })
                                .ToListAsync();
            return View(workouts);
        }

        // Tracked Workout Methods:

        /// <summary>
        /// Starts the tracking of a selected workout.
        /// </summary>
        /// <param name="workoutId">Workout Id being tracked.</param>
        /// <returns>They view to track a workout.</returns>
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> TrackWorkout(int workoutId)
        {
            var workout = await _context.Workouts
                                .Include(w => w.WorkoutExercises)
                                .ThenInclude(we => we.Exercise)
                                .FirstOrDefaultAsync(w => w.WorkoutId == workoutId);

            if (workout == null)
            {
                return NotFound(); 
            }

            var exercisesViewModels = workout.WorkoutExercises
                                    .Select(we => new ExerciseViewModel
                                    {
                                        Id = we.Exercise.ExerciseId,
                                        Name = we.Exercise.Name,
                                        IsCompleted = false // Default value
                                    }).ToList();

            var viewModel = new TrackedWorkoutViewModel
            {
                WorkoutName = workout.Name,
                WorkoutId = workout.WorkoutId,            
                DateCompleted = DateTime.Now, // Default to current date
                Exercises = exercisesViewModels
            };
            return View(viewModel);
        }


        // Tracked Workout Methods:

        /// <summary>
        /// Tracks the workout to the database when you click track in the view.
        /// </summary>
        /// <param name="model">Information about the workout being tracked.</param>
        /// <returns>Back to the user dashboard.</returns>
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> TrackWorkout(TrackedWorkoutViewModel model)
        
        {
            // Code to help figure out model validation errors
            //var errors = ModelState
            //.Where(x => x.Value.Errors.Count > 0)
            //.Select(x => new { x.Key, x.Value.Errors })
            //.ToArray();
            
            if (ModelState.IsValid)
            {
                // Getting the IdentityUserId of the logged in user
                var identityUserId = _userManager.GetUserId(User);

                
                var account = await _context.Accounts
                                            .FirstOrDefaultAsync(a => a.IdentityUserId == identityUserId);

                if (account == null)
                {
                    // If this hits something is wrong/ no user was found
                    return NotFound();
                }

                var trackedWorkout = new TrackedWorkout
                {
                    WorkoutId = model.WorkoutId,
                    AccountId = account.AccountId,
                    DateCompleted = model.DateCompleted,
                    
                };

                _context.TrackedWorkouts.Add(trackedWorkout);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index"); // Go back tothe  dashboard
            }

            return View(model); // Return the form view for corrections if model state is invalid
        }


        // ...End of Tracked Workout methods....



        // Implementing Messaging feature action methods now
        /// <summary>
        /// Takes the user to the send message view and prepares it to be used.
        /// </summary>
        /// <returns>The view for sending a message. With the trainers, exercises, and workouts to choose from.</returns>
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> SendMessage()
        {
            var trainersList = await GetTrainersList();
            var workoutsList = await GetWorkoutsList();
            var exercisesList = await GetExercisesList();
            var viewModel = new MessageViewModel
            {
                Trainers = trainersList,
                Workouts = workoutsList,
                Exercises = exercisesList                          
            };
            return View(viewModel);
        }


        /// <summary>
        /// Sends the message after the form has been filled out correctly.
        /// </summary>
        /// <param name="model">All the message info including the content, trainer, workout, and exercises specified.</param>
        /// <returns>Back to the user dashboard.</returns>
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> SendMessage(MessageViewModel model)
        {
           // var errors = ModelState
           //.Where(x => x.Value.Errors.Count > 0)
           //.Select(x => new { x.Key, x.Value.Errors })
           //.ToArray();
            if (ModelState.IsValid) 
            {
                var senderAccount = await _context.Accounts.FirstOrDefaultAsync(a => a.IdentityUserId == _userManager.GetUserId(User));
                
                if (senderAccount == null)
                {                   
                    return NotFound("Sender account not found.");
                }
                var message = new Message
                {
                    SenderId = senderAccount.AccountId,
                    RecipientId = model.RecipientId,
                    Content = model.Content,

Fitness_App_Final/WorkoutTrackingApp/Views/UserProfileDashboard/Index.cshtml
@model WorkoutTrackingApp.ViewModels.UserDashboardViewModel

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    //<h1>UserDashBoard</h1>
    ViewData["Title"] = "User Dashboard";   
}


<div class = "container my-5">
    
        <div class="row">
            <!-- Left Column -->
            <div class="col-md-6 text-md-start text-center">
                <a class="btn btn-success ms-md-2 mt-2 mt-md-0" asp-controller="UserProfileDashboard" asp-action="SelectedWorkouts">Track A Workout</a>
                <a class="btn btn-primary mb-2 mb-md-0" asp-controller="Workouts" asp-action="Index">View Workouts</a>
                
            </div>

            <!-- Right Column -->
            <div class="col-md-6 text-md-end text-center mt-3 mt-md-0">
                <a href="@Url.Action("SendMessage", "UserProfileDashboard")" class="btn btn-primary mb-2">Send Message to Trainer</a><br>
                <a href="@Url.Action("ViewMessages", "UserProfileDashboard")" class="btn btn-secondary mb-2">View Messages</a><br>
                <a asp-page="/SubscriberProfile" class="btn btn-info">View your Profile</a><br>
            </div>
        </div>
    
    <br>

    <h2 class = "text-center mb-3>Welcome back, @Model.UserName!</h2>

    <div class="row justify-content-center">
        <div class="row justify-content-center">
            <div class = "card h-100">
                <div class = "card-body">
                    <h3 class="card-title">User Details</h3>
                    <p>Email: @Model.Email</p>
                    <p>Subscription Status: @(Model.IsSubscribed ? $"Active until @Model.SubscriptionEndDate.ToString(\"MM/dd/yyyy\")" : "Not Subscribed")</p>
                 </div>
            </div>
         </div>
         <br>
        <div class="row justify-content-center">
             <div class = "card h-100">
                 <div class = "card-body">
                     <h3 class = "card-title">Recent Workouts</h3>
                     @if (Model.RecentWorkouts.Any())
                     {
                         
                         <ul class="list-group list-group-flush">
                             @foreach (var workout in Model.RecentWorkouts)
                             {            
                                 <li class="list-group-item">
                                <h3>@workout.Name</h3>
                                <p>@workout.Description</p>
                                <p>Completed on: @workout.DateCompleted?.ToString("MM/dd/yyyy")</p>
                                </li>
                             }
                        </ul>
                    }
                    else
                    {
                        <p class="text-muted">No recent workouts found.</p>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

Fitness_App_Final/WorkoutTrackingApp/Views/UserProfileDashboard/SelectedWorkouts.cshtml
@model IEnumerable<WorkoutTrackingApp.ViewModels.WorkoutViewModel>



<h2>Select a Workout</h2>

@foreach (var workout in Model)
{
    <div>
        <h3>@workout.Name</h3>
        <p>@workout.Description</p>
        <!-- Button to track this workout -->
        <form asp-action="TrackWorkout" asp-controller="UserProfileDashboard" method="get">
            <input type="hidden" name="workoutId" value="@workout.WorkoutID" />
            <button type="submit" class="btn btn-primary">Track this Workout</button>
        </form>
    </div>
}

Fitness_App_Final/WorkoutTrackingApp/Views/UserProfileDashboard/SendMessage.cshtml
@model WorkoutTrackingApp.ViewModels.MessageViewModel

@{
    ViewData["Title"] = "Send Message";
}

<h2>Send a Message to a Trainer</h2>

<form asp-action="SendMessage" method="post">
    <div class="form-group">
        <label asp-for="RecipientId">Select Trainer:</label>
        <select asp-for="RecipientId" asp-items="Model.Trainers" class="form-control"></select>
    </div>

    <!-- Workouts dropdown -->
    <div class="form-group">
        <label asp-for="SelectedWorkoutId">Select Workout:</label>
        <select asp-for="SelectedWorkoutId" asp-items="Model.Workouts" class="form-control">
            <option value="">-- Select a Workout --</option>
        </select>
    </div>

    <!--Exercises dropdown-->
    <div class="form-group">
        <label asp-for="SelectedExerciseId">Select Exercise:</label>
        <select asp-for="SelectedExerciseId" asp-items="Model.Exercises" class="form-control">
            <option value="">-- Select an Exercise --</option>
        </select>
    </div>

    <div class="form-group">
        <label asp-for="Content">Message:</label>
        <textarea asp-for="Content" class="form-control"></textarea>
    </div>

 

    <button type="submit" class="btn btn-primary">Send Message</button>
</form>

Fitness_App_Final/WorkoutTrackingApp/Views/UserProfileDashboard/TrackWorkout.cshtml
@model WorkoutTrackingApp.ViewModels.TrackedWorkoutViewModel

<h2>Track Workout: @Model.WorkoutName</h2>

<form asp-action="TrackWorkout" asp-controller="UserProfileDashboard" method="post">
    <input type="hidden" asp-for="WorkoutId" />
    <div>
        <label asp-for="DateCompleted">Date Completed</label>
        <input asp-for="DateCompleted" type="date" />
    </div>

    <div>
        <label>Check off Completed Exercises:</label>
        @foreach (var exercise in Model.Exercises)
        {
            <div>
                <input type="hidden" asp-for="@exercise.Id" />
                <input type="hidden" asp-for="WorkoutName" />
                <input type="checkbox" asp-for="@exercise.IsCompleted" />
                <label asp-for="@exercise.IsCompleted">@exercise.Name</label>
            </div>
        }
    </div>

    <button type="submit" class="btn btn-primary">Track</button>
</form>

Fitness_App_Final/WorkoutTrackingApp/Views/UserProfileDashboard/ViewMessages.cshtml
@model IEnumerable<WorkoutTrackingApp.Models.Message>
@*@model IEnumerable<dynamic>*@
@{
    ViewData["Title"] = "View Messages";
    var userInfos = ViewBag.UserInfos as Dictionary<int, string>;
}

<h2>Your Messages</h2>

<table class="table">
    <thead>
        <tr>
            <th>Sender</th>
            <th>Recipient</th>
            <th>Message</th>
            <th>Workout</th>
            <th>Exercise</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var message in Model)
        {
            <tr>
                <td>@userInfos[message.SenderId]</td>
                <td>@userInfos[message.RecipientId]</td>
                <td>@message.Content</td>
                <td>@message.SelectedWorkout?.Name</td>
                <td>@message.SelectedExercise?.Name</td>
                
            </tr>
        }
    </tbody>
</table>